#pragma once

/**
 * Build-time policy values shared by the runtime models and facade.
 *
 * ESP-IDF supplies CONFIG_* values from Kconfig. Defaults keep standalone
 * LLVM host tests buildable without sdkconfig; production values are fixed
 * when the firmware is built and are not mutable through the public API.
 */

/* ESP-IDF exposes the project's Kconfig values through sdkconfig.h.  The
 * host-only tests do not provide that generated header, so retain the
 * documented fallback values below for freestanding builds. */
#if defined(ESP_PLATFORM)
#include "sdkconfig.h"
#endif

#ifndef CONFIG_NETWORK_MANAGER_INITIAL_ATTEMPT_TIMEOUT_MS
#define CONFIG_NETWORK_MANAGER_INITIAL_ATTEMPT_TIMEOUT_MS 6000U
#endif
#ifndef CONFIG_NETWORK_MANAGER_WIFI_CONNECT_STABLE_MS
#define CONFIG_NETWORK_MANAGER_WIFI_CONNECT_STABLE_MS 10000U
#endif
#ifndef CONFIG_NETWORK_MANAGER_WIFI_DISCONNECT_STABLE_MS
#define CONFIG_NETWORK_MANAGER_WIFI_DISCONNECT_STABLE_MS 3000U
#endif
#ifndef CONFIG_NETWORK_MANAGER_WIFI_RETRY_LIMIT
#define CONFIG_NETWORK_MANAGER_WIFI_RETRY_LIMIT 10U
#endif
#ifndef CONFIG_NETWORK_MANAGER_WIFI_RETRY_INITIAL_BACKOFF_MS
#define CONFIG_NETWORK_MANAGER_WIFI_RETRY_INITIAL_BACKOFF_MS 1000U
#endif
#ifndef CONFIG_NETWORK_MANAGER_WIFI_RETRY_MAX_BACKOFF_MS
#define CONFIG_NETWORK_MANAGER_WIFI_RETRY_MAX_BACKOFF_MS 30000U
#endif
#ifndef CONFIG_NETWORK_MANAGER_WIFI_RETRY_UNLIMITED
#define CONFIG_NETWORK_MANAGER_WIFI_RETRY_UNLIMITED 0
#endif
#ifndef CONFIG_NETWORK_MANAGER_CELLULAR_INITIAL_IPV4_WAIT_MS
#define CONFIG_NETWORK_MANAGER_CELLULAR_INITIAL_IPV4_WAIT_MS 20000U
#endif
#ifndef CONFIG_NETWORK_MANAGER_CELLULAR_POWER_OFF_HOLD_MS
#define CONFIG_NETWORK_MANAGER_CELLULAR_POWER_OFF_HOLD_MS 1000U
#endif

#define NETWORK_MANAGER_INITIAL_ATTEMPT_TIMEOUT_MS \
    CONFIG_NETWORK_MANAGER_INITIAL_ATTEMPT_TIMEOUT_MS
#define NETWORK_MANAGER_WIFI_CONNECT_STABLE_MS \
    CONFIG_NETWORK_MANAGER_WIFI_CONNECT_STABLE_MS
#define NETWORK_MANAGER_WIFI_DISCONNECT_STABLE_MS \
    CONFIG_NETWORK_MANAGER_WIFI_DISCONNECT_STABLE_MS
#define NETWORK_MANAGER_WIFI_RETRY_LIMIT \
    CONFIG_NETWORK_MANAGER_WIFI_RETRY_LIMIT
#define NETWORK_MANAGER_WIFI_RETRY_INITIAL_BACKOFF_MS \
    CONFIG_NETWORK_MANAGER_WIFI_RETRY_INITIAL_BACKOFF_MS
#define NETWORK_MANAGER_WIFI_RETRY_MAX_BACKOFF_MS \
    CONFIG_NETWORK_MANAGER_WIFI_RETRY_MAX_BACKOFF_MS
#define NETWORK_MANAGER_WIFI_RETRY_UNLIMITED \
    CONFIG_NETWORK_MANAGER_WIFI_RETRY_UNLIMITED
#define NETWORK_MANAGER_CELLULAR_INITIAL_IPV4_WAIT_MS \
    CONFIG_NETWORK_MANAGER_CELLULAR_INITIAL_IPV4_WAIT_MS
#define NETWORK_MANAGER_CELLULAR_POWER_OFF_HOLD_MS \
    CONFIG_NETWORK_MANAGER_CELLULAR_POWER_OFF_HOLD_MS
