#pragma once

#define BOARD_LAIWFS300_GPIO_UNASSIGNED (-1)

#define BOARD_LAIWFS300_SIGNAL_MOTOR_IN1 "IN1"
#define BOARD_LAIWFS300_SIGNAL_MOTOR_IN2 "IN2"
#define BOARD_LAIWFS300_SIGNAL_MOTOR_IN3 "IN3"
#define BOARD_LAIWFS300_SIGNAL_MOTOR_IN4 "IN4"

#define BOARD_LAIWFS300_SIGNAL_LCD_SPI_MOSI "SPI2_MOSI"
#define BOARD_LAIWFS300_SIGNAL_LCD_SPI_SCK  "SPI2_SCK"
#define BOARD_LAIWFS300_SIGNAL_LCD_SPI_CS0  "SPI2_CS0"
#define BOARD_LAIWFS300_SIGNAL_TF_SPI_CS1   "SPI2_CS1"

#define BOARD_LAIWFS300_SIGNAL_TF_CD     "TF_CD"
#define BOARD_LAIWFS300_SIGNAL_USIM_DET  "USIM_DET"
#define BOARD_LAIWFS300_SIGNAL_SW_ADC    "SW_ADC"
