#pragma once

#include <stdint.h>

#define COMPANION_CORE_CONTRACT_VERSION 1U

typedef enum {
    COMPANION_PRODUCT_BOOTING = 0,
    COMPANION_PRODUCT_WAIT_NETWORK,
    COMPANION_PRODUCT_IDLE,
    COMPANION_PRODUCT_LOCATING,
    COMPANION_PRODUCT_TURNING,
    COMPANION_PRODUCT_CONNECTING,
    COMPANION_PRODUCT_LISTENING,
    COMPANION_PRODUCT_PROCESSING,
    COMPANION_PRODUCT_SPEAKING,
    COMPANION_PRODUCT_ERROR,
    COMPANION_PRODUCT_STATE_COUNT,
} companion_product_state_t;

typedef enum {
    COMPANION_TURN_NONE = 0,
    COMPANION_TURN_LEFT,
    COMPANION_TURN_RIGHT,
    COMPANION_TURN_DIRECTION_COUNT,
} companion_turn_direction_t;
