#ifndef OFDM_PROFILE_H
#define OFDM_PROFILE_H

#define OFDM_NORMAL_TX_PROFILE_INDEX 2U
#define OFDM_NORMAL_RX_GAIN_INDEX 1U
#define OFDM_NORMAL_OUTPUT_VOLUME_PERCENT 90U
#define OFDM_NORMAL_INPUT_GAIN_DB 30.0F
#define OFDM_NORMAL_PCM_SCALE 24000U

#define OFDM_NORMAL_FIRST_CARRIER_BIN 32U
#define OFDM_NORMAL_LAST_CARRIER_BIN 59U
#define OFDM_NORMAL_PILOT_BIN_0 34U
#define OFDM_NORMAL_PILOT_BIN_1 42U
#define OFDM_NORMAL_PILOT_BIN_2 50U
#define OFDM_NORMAL_PILOT_BIN_3 58U
#define OFDM_NORMAL_PILOT_COUNT 4U
#define OFDM_NORMAL_DATA_CARRIER_COUNT \
    (OFDM_NORMAL_LAST_CARRIER_BIN - OFDM_NORMAL_FIRST_CARRIER_BIN + 1U - \
     OFDM_NORMAL_PILOT_COUNT)

#endif
