#include "rc_video_format.h"

#define TEST_ASSERT(cond) do { if (!(cond)) return __LINE__; } while (0)

int main(void)
{
    TEST_ASSERT(240U == RC_VIDEO_ENCODE_WIDTH);
    TEST_ASSERT(180U == RC_VIDEO_ENCODE_HEIGHT);
    TEST_ASSERT(RC_VIDEO_ENCODE_WIDTH * 3U == RC_VIDEO_ENCODE_HEIGHT * 4U);
    TEST_ASSERT(RC_VIDEO_ENCODE_WIDTH * RC_VIDEO_ENCODE_HEIGHT < 320U * 240U);
    TEST_ASSERT(320U == RC_VIDEO_DISPLAY_WIDTH);
    TEST_ASSERT(240U == RC_VIDEO_DISPLAY_HEIGHT);
    TEST_ASSERT(60U == RC_VIDEO_JPEG_QUALITY);
    TEST_ASSERT(RC_VIDEO_JPEG_QUALITY > 0U && RC_VIDEO_JPEG_QUALITY <= 100U);
    return 0;
}
